[project]
name = "repl-nix-workspace"
version = "0.1.3"
description = "haha tymofii bomb go brrr"
requires-python = ">=3.11"
dependencies = [
    "eventlet>=0.40.3",
    "flask>=3.1.2",
    "flask-socketio>=5.5.1",
    "python-socketio>=5.14.3",
]

[tool.poetry]
package-mode = false
